### ISSUE TITLE
Anzeigefehler

### ISSUE THREAD

**Issue by Jonas74** [epha/matrix#54]
Example: Aspirin und Similisan. Menu Liste does not work correctly on select and deselect. No reset if click on matrix in header.

**Comment by ephaee** [comment]
https://matrix.epha.ch/#/gtin:45116,08537/

**Comment by ephaee** [comment]
New behaviour: if atc equals "Nicht klassifizierbar" https://github.com/epha/matrix/commit/5c1246e627a408c274b0f31bff8078d1bd21de28#diff-579d22df0f98570f8d5b5b1ef9a0c8d8R761 or in other words if we dont have a sustance: it will use the remedy information instead of substance. This has a positive effect that the interaction algorithm does not break. The rememdy information will be displayed below the product name see screenshot:

![screen shot 2015-03-18 at 11 00 22](https://cloud.githubusercontent.com/assets/5112286/6706495/96fef59e-cd5e-11e4-997e-e5abb26654c0.png)
